In [1]:
%reload_ext autoreload
%autoreload 2
import tensorflow as tf
import sys
import math
import numpy as np
sys.path.append('../../pytools')
import d2l

d2l.gpu_mem_init()

2025-09-19 11:04:35.492518: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-09-19 11:04:35.555496: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-09-19 11:04:36.997055: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.


Memory growth enabled for PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'): True


In [15]:
class MyDense(tf.keras.Model):
    def __init__(self, units):
        super().__init__()
        self.units = units
    def build(self, x_shape):
        self.weight = self.add_weight(name='weight', shape=[x_shape[-1], self.units], initializer=tf.random_normal_initializer())
        self.bias = self.add_weight(name='bias', shape=[self.units], initializer=tf.zeros_initializer())
    def call(self, x):
        x= tf.matmul(x, self.weight) + self.bias
        return tf.nn.relu(x)


In [16]:
dense = MyDense(3)
dense(tf.random.uniform((2,5)))
print(dense.weights)

[<Variable path=my_dense_8/weight, shape=(5, 3), dtype=float32, value=[[ 0.05522285 -0.07114355  0.09311229]
 [-0.02980409 -0.0380142   0.01665183]
 [ 0.0165642  -0.00753567  0.00284316]
 [-0.01843435  0.01787244  0.04961246]
 [-0.01341775  0.00791334  0.02497029]]>, <Variable path=my_dense_8/bias, shape=(3,), dtype=float32, value=[0. 0. 0.]>]


In [23]:
net = tf.keras.Sequential([MyDense(8), MyDense(1)])
x = tf.random.uniform((2,20))
net(x)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.00912208],
       [0.01199578]], dtype=float32)>