In [1]:
%reload_ext autoreload
%autoreload 2
import tensorflow as tf
import sys
import math
import numpy as np
sys.path.append('../../pytools')
import d2l
import collections
import re
import random

d2l.gpu_mem_init()

2025-09-25 16:17:35.259922: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-09-25 16:17:35.322521: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-09-25 16:17:36.781677: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.


Memory growth enabled for PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU'): True


In [2]:
X, W_xh = tf.random.normal((3, 1), 0, 1), tf.random.normal((1, 4), 0, 1)
H, W_hh = tf.random.normal((3, 4), 0, 1), tf.random.normal((4, 4), 0, 1)
tf.matmul(X, W_xh) + tf.matmul(H, W_hh)

I0000 00:00:1758788708.465929 4052801 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 30827 MB memory:  -> device: 0, name: Tesla V100-SXM2-32GB, pci bus id: 0000:00:08.0, compute capability: 7.0


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 3.7836046, -1.6110873, -1.5293003,  2.935429 ],
       [ 4.556457 , -2.0818865, -5.4820566, -1.498403 ],
       [-8.119227 ,  1.2493953,  1.2303269, -0.5417452]], dtype=float32)>

In [3]:
tf.matmul(tf.concat((X, H), 1), tf.concat((W_xh, W_hh), 0))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 3.7836044, -1.6110873, -1.5293002,  2.935429 ],
       [ 4.5564575, -2.0818865, -5.4820566, -1.498403 ],
       [-8.119227 ,  1.2493951,  1.2303268, -0.5417452]], dtype=float32)>