In [1]:
import tensorflow as tf

2025-09-07 16:16:14.430135: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-09-07 16:16:14.492262: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-09-07 16:16:15.991571: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.


In [2]:
print(tf.__version__)

2.20.0


In [3]:
x = tf.Variable(tf.range(4, dtype=tf.float32))
x

I0000 00:00:1757232976.923413 4055161 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 31135 MB memory:  -> device: 0, name: Tesla V100-SXM2-32GB, pci bus id: 0000:00:08.0, compute capability: 7.0


<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([0., 1., 2., 3.], dtype=float32)>

In [4]:
with tf.GradientTape() as t:
    y = tf.tensordot(x, x, axes=0)
y

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]], dtype=float32)>

In [5]:
grad = t.gradient(y, x)
grad

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([12., 12., 12., 12.], dtype=float32)>

In [6]:
a = tf.reshape(tf.range(12, dtype=tf.float32), (2,3,2))
a

<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
array([[[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.]],

       [[ 6.,  7.],
        [ 8.,  9.],
        [10., 11.]]], dtype=float32)>

In [7]:
b = tf.reshape(tf.range(24, dtype=tf.float32), (3,2,4))
b

<tf.Tensor: shape=(3, 2, 4), dtype=float32, numpy=
array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]],

       [[16., 17., 18., 19.],
        [20., 21., 22., 23.]]], dtype=float32)>

In [8]:
c = tf.tensordot(a, b, axes=2)
c

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[220., 235., 250., 265.],
       [580., 631., 682., 733.]], dtype=float32)>

In [9]:
va = tf.Variable(a)
vb = tf.Variable(b)
with tf.GradientTape(persistent=True) as t:
    y = tf.tensordot(va, vb, axes=2)
y

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[220., 235., 250., 265.],
       [580., 631., 682., 733.]], dtype=float32)>

In [10]:
grad = t.gradient(y, va)
grad

<tf.Tensor: shape=(2, 3, 2), dtype=float32, numpy=
array([[[ 6., 22.],
        [38., 54.],
        [70., 86.]],

       [[ 6., 22.],
        [38., 54.],
        [70., 86.]]], dtype=float32)>

In [11]:
grad_b = t.gradient(y, vb)
grad_b

<tf.Tensor: shape=(3, 2, 4), dtype=float32, numpy=
array([[[ 6.,  6.,  6.,  6.],
        [ 8.,  8.,  8.,  8.]],

       [[10., 10., 10., 10.],
        [12., 12., 12., 12.]],

       [[14., 14., 14., 14.],
        [16., 16., 16., 16.]]], dtype=float32)>

In [12]:
prob = tf.ones(6) / 6
prob

<tf.Tensor: shape=(6,), dtype=float32, numpy=
array([0.16666667, 0.16666667, 0.16666667, 0.16666667, 0.16666667,
       0.16666667], dtype=float32)>

In [13]:
import tensorflow_probability as tfp
tfp.distributions.Multinomial(1, prob).sample()

2025-09-07 16:16:18.247361: W external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:237] Falling back to the CUDA driver for PTX compilation; ptxas does not support CC 7.0
2025-09-07 16:16:18.247383: W external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:240] Used ptxas at /usr/local/cuda/bin/ptxas
2025-09-07 16:16:18.247425: W tensorflow/compiler/mlir/tools/kernel_gen/transforms/gpu_kernel_to_blob_pass.cc:188] Failed to compile generated PTX with ptxas. Falling back to compilation by driver.
2025-09-07 16:16:18.391252: W tensorflow/compiler/mlir/tools/kernel_gen/transforms/gpu_kernel_to_blob_pass.cc:188] Failed to compile generated PTX with ptxas. Falling back to compilation by driver.
2025-09-07 16:16:18.393348: W tensorflow/compiler/mlir/tools/kernel_gen/transforms/gpu_kernel_to_blob_pass.cc:188] Failed to compile generated PTX with ptxas. Falling back to compilation by driver.
2025-09-07 16:16:18.395594: W tensorflow/compiler/mlir/tools/kernel_gen/t

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([0., 0., 0., 0., 0., 1.], dtype=float32)>

In [14]:
tfp.distributions.Multinomial(5, prob).sample()

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([0., 0., 2., 0., 2., 1.], dtype=float32)>

In [15]:
prob = tf.range(6) / 6
prob

<tf.Tensor: shape=(6,), dtype=float64, numpy=
array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333])>

In [16]:
tfp.distributions.Multinomial(3, prob).sample()

2025-09-07 16:16:21.554345: W tensorflow/compiler/mlir/tools/kernel_gen/transforms/gpu_kernel_to_blob_pass.cc:188] Failed to compile generated PTX with ptxas. Falling back to compilation by driver.


2025-09-07 16:16:21.689736: W tensorflow/compiler/mlir/tools/kernel_gen/transforms/gpu_kernel_to_blob_pass.cc:188] Failed to compile generated PTX with ptxas. Falling back to compilation by driver.
2025-09-07 16:16:21.691704: W tensorflow/compiler/mlir/tools/kernel_gen/transforms/gpu_kernel_to_blob_pass.cc:188] Failed to compile generated PTX with ptxas. Falling back to compilation by driver.
2025-09-07 16:16:21.694554: W tensorflow/compiler/mlir/tools/kernel_gen/transforms/gpu_kernel_to_blob_pass.cc:188] Failed to compile generated PTX with ptxas. Falling back to compilation by driver.
2025-09-07 16:16:21.696718: W tensorflow/compiler/mlir/tools/kernel_gen/transforms/gpu_kernel_to_blob_pass.cc:188] Failed to compile generated PTX with ptxas. Falling back to compilation by driver.
2025-09-07 16:16:21.699111: W tensorflow/compiler/mlir/tools/kernel_gen/transforms/gpu_kernel_to_blob_pass.cc:188] Failed to compile generated PTX with ptxas. Falling back to compilation by driver.
2025-09-07

<tf.Tensor: shape=(6,), dtype=float64, numpy=array([0., 0., 0., 0., 2., 1.])>

In [17]:
import tensorflow as tf

In [18]:
print(dir(tf.reduce_mean))

['__annotations__', '__builtins__', '__call__', '__class__', '__closure__', '__code__', '__defaults__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__get__', '__getattribute__', '__globals__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__kwdefaults__', '__le__', '__lt__', '__module__', '__name__', '__ne__', '__new__', '__original_wrapped__', '__qualname__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__signature__', '__sizeof__', '__str__', '__subclasshook__', '__wrapped__', '_tf_decorator', '_tf_fallback_dispatchers', '_tf_type_based_dispatcher']


In [19]:
help(tf.ones)

Help on function ones in module tensorflow.python.ops.array_ops:

ones(shape, dtype=tf.float32, name=None, layout=None)
    Creates a tensor with all elements set to one (1).
    
    See also `tf.ones_like`, `tf.zeros`, `tf.fill`, `tf.eye`.
    
    This operation returns a tensor of type `dtype` with shape `shape` and
    all elements set to one.
    
    >>> tf.ones([3, 4], tf.int32)
    <tf.Tensor: shape=(3, 4), dtype=int32, numpy=
    array([[1, 1, 1, 1],
           [1, 1, 1, 1],
           [1, 1, 1, 1]], dtype=int32)>
    
    Args:
      shape: A `list` of integers, a `tuple` of integers, or a 1-D `Tensor` of
        type `int32`.
      dtype: Optional DType of an element in the resulting `Tensor`. Default is
        `tf.float32`.
      name: Optional string. A name for the operation.
      layout: Optional, `tf.experimental.dtensor.Layout`. If provided, the result
        is a [DTensor](https://www.tensorflow.org/guide/dtensor_overview) with the
        provided layout.
    
  

In [20]:
help(tf.gradients)

Help on function gradients_v2 in module tensorflow.python.ops.gradients_impl:

gradients_v2(ys, xs, grad_ys=None, name='gradients', gate_gradients=False, aggregation_method=None, stop_gradients=None, unconnected_gradients=<UnconnectedGradients.NONE: 'none'>)
    Constructs symbolic derivatives of sum of `ys` w.r.t. x in `xs`.
    
    `tf.gradients` is only valid in a graph context. In particular,
    it is valid in the context of a `tf.function` wrapper, where code
    is executing as a graph.
    
    `ys` and `xs` are each a `Tensor` or a list of tensors.  `grad_ys`
    is a list of `Tensor`, holding the gradients received by the
    `ys`. The list must be the same length as `ys`.
    
    `gradients()` adds ops to the graph to output the derivatives of `ys` with
    respect to `xs`.  It returns a list of `Tensor` of length `len(xs)` where
    each tensor is the `sum(dy/dx)` for y in `ys` and for x in `xs`.
    
    `grad_ys` is a list of tensors of the same length as `ys` that hold

In [21]:
!nvidia-smi

Sun Sep  7 16:16:23 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.158.01             Driver Version: 570.158.01     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla V100-SXM2-32GB           On  |   00000000:00:08.0 Off |                    0 |
| N/A   39C    P0             54W /  300W |   31457MiB /  32768MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [22]:
import time
class Timer:  #@save
    """记录多次运行时间"""
    def __init__(self):
        self.times = []
        self.start()

    def start(self):
        """启动计时器"""
        self.tik = time.time()

    def stop(self):
        """停止计时器并将时间记录在列表中"""
        self.times.append(time.time() - self.tik)
        return self.times[-1]

    def avg(self):
        """返回平均时间"""
        return sum(self.times) / len(self.times)

    def sum(self):
        """返回时间总和"""
        return sum(self.times)

    def cumsum(self):
        """返回累计时间"""
        return np.array(self.times).cumsum().tolist()

In [23]:
n = 1000
a = tf.Variable(tf.ones(n))
b = tf.Variable(tf.ones(n))
c = tf.Variable(tf.zeros(n))

In [24]:
timer = Timer()
for i in range(n):
    c[i].assign(a[i] + b[i])
f'{timer.stop():.5f} sec'

'1.28958 sec'

In [25]:
timer.start()
c = a + b
f'{timer.stop(): .5f} sec'

' 0.00130 sec'

In [26]:
import sys
import os
sys.path.append('../pytools')
from d2l import construct_data

: 